<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ServiceExtencions\**" />
    <EmbeddedResource Remove="ServiceExtencions\**" />
    <None Remove="ServiceExtencions\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mantenimiento.Core\Mantenimiento.Core.Domain.csproj" />
  </ItemGroup>

</Project>
