<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ServiceExtencions\**" />
    <EmbeddedResource Remove="ServiceExtencions\**" />
    <None Remove="ServiceExtencions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mantenimiento.Core\Mantenimiento.Core.Domain.csproj" />
  </ItemGroup>

</Project>
